### ISSUE TITLE
Index_set_sortedvector

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#18]
Обновить свою ветку по main.
Создать файл source/index_set_sortedvector.cpp.
В нём определить класс ogxx::Index_set_sortedvector: public ogxx::Index_set, ogxx::Indexed_iterable\<Scalar_index\>.
Реализовать интерфейс множества на основе упорядоченного vector\<Scalar_index\> (поиск за логарифмическое время).
Для реализации итератора использовать source/stl_iterator.hpp.

Близкие задачи у Александра Кайгородова и Ивана Мартынова.

**Comment by NasonenkoID** [comment]
Дмитрий Рустамович, здравствуйте! Неделю назад выполнил задание, но забыл вас оповестить. Извините!

**Comment by NasonenkoID** [comment]
В своей ветке добавил необходимый файл, он в папке source.

**Comment by kuvshinovdr** [comment]
Переименуйте, пожалуйста, [index_set_sortedvector.cpp.](https://github.com/kuvshinovdr/OGxx/blob/pm2-nasonenko-i-d/source/index_set_sortedvector.cpp.) в index_set_sortedvector.cpp, там лишняя точка в конце.  Из-за этого у меня эта ветка даже не открывается -- только через браузер могу смотреть.

**Comment by NasonenkoID** [comment]
Переименовал файл.

**Comment by kuvshinovdr** [comment]
Я внёс правки в файл (надо загрузить).
1. Добавьте документирующий комментарий в начале файла (по аналогии с прочими файлами в проекте).
2. Не забывайте инклюды (добавлены мной).
3. Методы должны соответствовать реализуемым интерфейсам.

**Comment by NasonenkoID** [comment]
Дмитрий Рустамович, я постарался исправить код. Посмотрите, пожалуйста!

**Comment by NasonenkoID** [comment]
Дмитрий Рустамович, здравствуйте! Вы видели мой комментарий? Боюсь, что вы могли его пропустить.

**Comment by kuvshinovdr** [comment]
Да, пропустил. Просмотрел, внёс правки и запушил в вашу ветку. Можете написать тест на него?

**Comment by NasonenkoID** [comment]
Не совсем понимаю, что именно нужно протестировать. Можете разъяснить, пожалуйста?

**Comment by kuvshinovdr** [comment]
Добавил тест в tests/index_set_sortedvector.cpp, взгляните. Добавьте ещё один TEST_CASE с чем-то похожим, но созданием объекта Index_set_sortedvector (как Index_set) с помощью new_index_set_sortedvector (эти функции объявлены в st_set.hpp, а определены в source/index_set_sortedvector.cpp) от итератора (объекта Index_iterator_uptr, его можно создать, например, из массива с помощью new_stl_iterator, как это сделано в первом, уже готовом, TEST_CASE'е).

**Comment by NasonenkoID** [comment]
Здравствуйте, Дмитрий Рустамович! Я добавил еще один TEST_CASE в tests/index_set_sortedvector.cpp.

**Comment by kuvshinovdr** [comment]
Добрый день! (В принципе, в таких обсуждениях не принято писать приветствия 🙂)
Да, вижу. Внёс некоторые исправления, чтобы компилировалось (добавил в вашу ветку).
Код добавлен в main, задание выполнено.
