### ISSUE TITLE
Stl_iterator и iterator_algorithms

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#24]
1. Обновить свою ветку по main.
2. Скачать библиотеку doctest. Далее она должна быть доступна для 
```cpp
#include <doctest/doctest.h>
```
**Не добавлять её в репозиторий!**

3. Попробовать собрать и запустить tests/stl_iterator_and_iterator_algorithms.cpp.
4. Добавить тесты для оставшихся алгоритмов из ogxx/iterator_algorithms.hpp.
5. По возможности исправить обнаруженные ошибки.

**Comment by chaplyginmd** [comment]
Здравствуйте, я закинул папку OGxx в папку с проектами (использую Visual Studio), но  у меня не получается подключить внешние файлы таким способом: 
```c++
#include <ogxx/stl_iterator.hpp>
``` 
Все получается, если указать весь путь. Но проблема в том, что в подключаемых файлах тоже есть include, который подключает файлы из папки OGxx и там они тоже не видны. Помогите пожалуйста решить проблему

**Comment by kuvshinovdr** [comment]
Добавьте $(ProjectDir) во включаемые каталоги, а папку ogxx положите рядом с файлом проекта (в папку проекта). Тогда и doctest можно будет туда же кинуть.

![изображение](https://github.com/kuvshinovdr/OGxx/assets/135211050/6495c752-0c9d-4a79-b71f-01f5741a8a78)

**Comment by chaplyginmd** [comment]
Спасибо, все заработало

**Comment by chaplyginmd** [comment]
Задание сделал, смотрите последний коммит.

**Comment by kuvshinovdr** [comment]
Хорошо. Я несколько доработал вашу версию и внёс её в main, заодно обновил вашу ветку по main, чтобы избежать конфликтов слияния. Задача засчитана.
