### ISSUE TITLE
edge_list_io_print

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#26]
Обновите ветку. В include/ogxx должен появиться файл edge_list_io.hpp.
В source создайте файл edge_list_io_print.cpp.
В нём разместите реализацию двух функций ogxx::io::print из указанного заголовочного файла.
В tests создайте файл edge_list_io_print.cpp (это уже другой файл).
В нём напишите тест версии print, принимающей произвольный ostream (вторая версия попросту должна вызывать первую для std::cout, поэтому её тестировать не будем).
Тест должен использовать библиотеку doctest. В качестве примера можете использовать уже имеющиеся в tests файлы.

**Comment by kuvshinovdr** [comment]
Чтобы написать тест, надо будет иметь функцию, создающую Edge_list. Пока такой нет, но есть такое задание (Edge_list_vector).

**Comment by kuvshinovdr** [comment]
Добавление в main я делаю сам.

**Comment by Sa2rday** [comment]
У меня вроде получилось, можете проверить пожалуйста

**Comment by Sa2rday** [comment]
?

**Comment by Sa2rday** [comment]
Исправил, посмотрите ещё раз

**Comment by kuvshinovdr** [comment]
Что за файл ogxx/string_utils.hpp?

**Comment by kuvshinovdr** [comment]
Вам не требовалось реализовывать функцию чтения.

**Comment by Sa2rday** [comment]
я не добавлял string_utils, может это vs создал

**Comment by kuvshinovdr** [comment]
VS вряд ли мог добавить #include, тем более, с несуществующим файлом.

**Comment by Sa2rday** [comment]
мне нужно сейчас ещё что-то сделать, или оно зачтено и можно уже другую делать задачу

**Comment by kuvshinovdr** [comment]
А оно работает? Есть тест?

**Comment by Sa2rday** [comment]
я же все файлы скинул, оно не работает?

**Comment by kuvshinovdr** [comment]
Вы пытаетесь создать объект Edge_list, т.е. абстрактного класса. Значит, вы не пытались это скомпилировать, либо проигнорировали невозможность скомпилировать.

**Comment by kuvshinovdr** [comment]
Исправил и закоммитил в вашу ветку. Сравните.

**Comment by kuvshinovdr** [comment]
Код (без функции read, которой не было в этом задании) добавлен в main.
