### ISSUE TITLE
edge_list_io_read

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#27]
1. Обновите ветку. В include/ogxx должен появиться файл edge_list_io.hpp.
2. В source создайте файл edge_list_io_read.cpp.
3. В нём разместите реализацию двух функции ogxx::io::read из указанного заголовочного файла.
4. В tests создайте файл edge_list_io_read.cpp (это уже другой файл).
5. В нём напишите тест read.
Тест должен использовать библиотеку doctest. В качестве примера можете использовать уже имеющиеся в tests файлы.
Для теста понадобится создавать объекты Edge_list, но на данный момент нет ни одного конкретного класса, реализующего данный интерфейс. Такой класс у нас запланирован (Edge_list_vector), надеюсь, мы его скоро увидим.

**Comment by kuvshinovdr** [comment]
Использовать функцию util::accept_tokens из source/parsing_utils.hpp.

**Comment by kuvshinovdr** [comment]
Не надо копировать код из edge_list_io.hpp. Надо обновить ветку, чтобы данный файл появился в include и включать его в свой cpp-файл.

**Comment by kuvshinovdr** [comment]
Обновите ветку по main. Изменён интерфейс функции read:
```cpp
auto read(std::string_view& in, ogxx::Edge_list& el, Edge_list_format const& format)
  -> bool;
```
Данная функция должна парсить строку, которую видит через in в соответствии с форматом format и писать прочитанное в объект el. Возвращаем успех разбора (false -- возникла ошибка, true -- не было ошибки). Из объекта in удаляем прочитанный префикс (независимо от успешности).

**Comment by kuvshinovdr** [comment]
Я обновил вашу ветку, не забудьте сделать fetch.

**Comment by kuvshinovdr** [comment]
Можно ориентироваться на реализацию чтения St_matrix в файле source/st_matrix_io_read.cpp.

**Comment by kuvshinovdr** [comment]
Передаю задачу другому участнику.

**Comment by kuvshinovdr** [comment]
В source есть файл st_matrix_io_read.cpp, демонстрирующий способ парсинга, который я предполагал для данного и аналогичных заданий.

**Comment by chaplyginmd** [comment]
У меня есть сложности при написании кода. Я написал функцию, которая работает, если входной string_view ты в программе задаешь сам. Но к примеру, если ты считываешь что-то из файла и потом записываешь это в string_view, то формат может отличаться от того, что ты записал в файл, к примеру если я считываю список так:
```c++
std::string in, temp;
std::ifstream input("input.txt");
while (input)
{
	input >> temp;
	in += temp;
	if (temp == "{") break;
}
std::string_view test_in = in;
``` 
При этом пришлось немного переделать функцию accept_tokens, чтобы она не урезала пробелы, табуляцию и т.д. перед форматными токенами, потому что среди них встречаются те, которые начинаются с этих символов, и если применять вашу версию accept_tokens, то некоторые токены урезаются и строка неправильно парсится. Оставить эту версию или доработать, чтобы можно было из файла задавать string_view? Просто если делать второй вариант, то тогда формат который вы задали не будет единственно возможным, который будет восприниматься функцией как правильный. В реализованном на данный момент коде любой неверный символ будет считаться как неверный формат и список не считается.

**Comment by chaplyginmd** [comment]
Я сделал rebase от main, хотел запушить в свою ветку, но там написано force push origin. Все будет в порядке если запушить?

**Comment by chaplyginmd** [comment]
Все получилось.

**Comment by kuvshinovdr** [comment]
Хорошо. Посмотрю код.

**Comment by kuvshinovdr** [comment]
Не стоит менять поведение уже используемых функций, поскольку это ломает другой код. Если нужна другая версия, стоило именно её назвать по-другому.

**Comment by chaplyginmd** [comment]
т.е. просто поменять название функции? а сам алгоритм и подход правильный или необходимо переделать?

**Comment by kuvshinovdr** [comment]
Насчёт названий функций -- просто общие соображения. Там вроде не должно быть нужно учитывать так пробельные символы. Но я внимательно не проверял. На первоначальной версии accept_tokens тест не проходит?

**Comment by chaplyginmd** [comment]
Если использовать первоначальную версию accept_tokens, то надо немного код поменять, потому что эта версия обрезает пробельные символы у форматных токенов, поэтому приходится применять accept_tokens после применения функции ltrim к строке, которую парсим, потому что первая версия accept_tokens извлекает все, кроме разделителей, поэтому после ее применения остаются пробелы, которые мешают извлекать числа. По крайней мере, я не придумал другого способа как избавляться от этих оставшихся пробелов.

**Comment by kuvshinovdr** [comment]
Так там так и предполагалось. Эти пробельные символы в формате прописаны для вывода. На вводе они просто как необязательные разделители. Поэтому при парсинге надо ltrim всё время делать, и ввод edge_list{(0,1)(4,5)(5,6)} вообще без пробелов считается корректным и должен пройти.

**Comment by chaplyginmd** [comment]
Спасибо, понял, я это и хотел узнать

**Comment by chaplyginmd** [comment]
Переделал, смотрите последний коммит.

**Comment by kuvshinovdr** [comment]
Сортировка и удаление повторов, возможно, лишний момент. Ну, ладно. Я несколько расширил тесты и изменил код (если хотите, можете посмотреть два последних коммита в своей ветке), он добавлен в main. Задание засчитано.
