### ISSUE TITLE
Dense_bit_matrix

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#3]
Создать файл source/dense_bit_matrix.cpp.
В нём разместить класс ogxx::Dense_bit_matrix : public ogxx::Bit_matrix.
В качестве хранилища бит использовать vector&lt;unsigned&gt;.
Не vector&lt;bool&gt; потому, что vector&lt;bool&gt; не позволяет эффективно работать с диапазонами бит.

Реализовать методы:
* shape()
* reshape(Matrix_shape) (о содержимом можно не заботиться, т.е. можно использовать vector::resize)
* get(Matrix_index position)
* set(Matrix_index position, bool value)
* flip(Matrix_index position)
* fill(bool value)

Перед началом работы не забудьте обновить свою ветку по main (через rebase).

**Comment by kuvshinovdr** [comment]
Класс Dense_bit_matrix требуется для реализации другой задачи, желательно поскорее его получить.

**Comment by RomanTimashev** [comment]
такой вопрос а во всех ли функциях могу использовать override не очень понимаю

**Comment by RomanTimashev** [comment]
Вопрос а помимо самого файла что еще нужно загрузить тесты?

**Comment by kuvshinovdr** [comment]
1. Override пишем в тех функциях, которые определяют методы интерфейса (в базовом классе это virtual функции).
2. Тесты пока не требуются.

**Comment by RomanTimashev** [comment]
можно ли пользоваться assert при проверке например не вылезли мы за пределы вектора в функции get

**Comment by kuvshinovdr** [comment]
Проверять надо, но через if. В бит-матрице мы решили, что get возвращает false за пределами матрицы.

**Comment by RomanTimashev** [comment]
здравствуйте доделал последнюю функцию написал несколько заглушек хотел спросить подойдут ли они

**Comment by kuvshinovdr** [comment]
1. Обновил вашу ветку по ветке main и изменил кое-что в коде соответственно (вынес вычисление линейного индекса в отдельную функцию Matrix_index::linear_index).
2. Переименуйте bit_contain в _bit_contain или мб укоротить даже, типа _bits (тоже ведь private-член, поэтому _).
3. Заглушки должны бросать исключение типа такого:
```cpp
throw std::logical_error("Dense_bit_matrix::iterate_row not implemented");
```
4. Уточните состав методов, унаследованных из Bit_matrix. Там есть ещё методы.

**Comment by kuvshinovdr** [comment]
Код добавлен в main.
