### ISSUE TITLE
Edge_list_hashtable

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#32]
Обновить ветку по main.
Создать файл source/edge_list_hashtable.cpp.
В нём определить класс ogxx::Edge_list_hashtable: public ogxx::Edge_list, public ogxx::St_set\<Vertex_pair\> который должен реализовывать список/множество рёбер поверх std::unordered_set\<Vertex_pair\>. Для этого требуется реализовать хэш-функцию для типа Vertex_pair. Можно, например, сделать так:

```cpp
namespace std
{
  template <>
  struct hash<ogxx::Vertex_pair>
  {
    constexpr size_t operator()(ogxx::Vertex_pair p) const noexcept
    {
      hash<ogxx::Scalar_index> h;
      return h(p.first) * 15485863 ^ h(p.second);
    }
  };
}
```

**Comment by Vovanfh20** [comment]
Добрый день, Дмитрий Рустамович. Напомните ещё раз пожалуйста на какой файл вы мне рекомендовали опираться в прошлый четверг?

**Comment by Vovanfh20** [comment]
Я сделал новый код

**Comment by Vovanfh20** [comment]
Добрый вечер. Я установил приложение github и наконец разобрался что мне на самом деле нужно было делать. Я запушил сегодня код

**Comment by Vovanfh20** [comment]
Гефлинг Владимир Ильич. МХ - 201. Добрый день. Я передал первое задание

ср, 25 окт. 2023 г., 22:36 Dmitry R. Kuvshinov ***@***.***>:

**Comment by kuvshinovdr** [comment]
Не все чисто виртуальные функции Edge_list определены. См. базовые классы Edge_list.

**Comment by Vovanfh20** [comment]
Добрый вечер, доопределил оставшиеся функции

**Comment by kuvshinovdr** [comment]
Нет, похоже, вы меня неправильно поняли. То, что вы добавили, добавлять не следовало. "Оставшиеся функции" всё ещё не определены. Edge_list -- наследник Bag\<Vertex_pair\> и, через него, Sized_iterable\<Vertex_pair\> и Iterable\<Vertex_pair\>, значит, должны быть методы Bag\<Vertex_pair\>, Sized_iterable\<Vertex_pair\> и Iterable\<Vertex_pair\>.

**Comment by kuvshinovdr** [comment]
Код доработан и добавлен в ветки mx2-gefling-v-i и main.
