### ISSUE TITLE
graph_view_di_el.cpp

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#33]
1. Обновить свою ветку по main.
2. Создать файл source/graph_view_di_el.cpp
3. В нём определить класс ogxx::Graph_view_directed_edge_list: public ogxx::Graph_view.
4. В данный класс в качестве поля добавить ссылку на Edge_list (инициализировать конструктором).
5. Реализовать методы Graph_view поверх Edge_list, предполагая, что это орграф.
6. В том же файле реализовать функцию ogxx::directed::graph_view(Edge_list& el), которая будет возвращать новый объект ogxx::Graph_view_directed_edge_list, инициализированный ссылкой el.

**Comment by kuvshinovdr** [comment]
Добавлен source/graph_view_di_al.cpp, реализующий directed::graph_view для Adjacency_list.

**Comment by AinurAbdullaeva** [comment]
Проверьте пожалуйста, то что я добавила

**Comment by kuvshinovdr** [comment]
Я внёс некоторые правки и закоммитил в вашу ветку -- см. обновление. Получится ли скомпилировать данный файл?

**Comment by kuvshinovdr** [comment]
Задача принята, код добавлен в main.
