### ISSUE TITLE
STL iterator

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#4]
Создать файл source/stl_iterator.cpp.
В нём реализовать класс ogxx::Stl_iterator<T, It, Sent>: public Basic_iterator&lt;T&gt; (абстрактный базовый класс определён в include/iterator.hpp). Поля Stl_iterator<T, It, Sent>:
* It current
* Sent end

Реализовать метод next(T& out_item). 
На каждом вызове next итератор current сравнивается с end. Если они равны, то next возвращает false. Иначе записываем out_item = *current, продвигаем current вперёд и возвращаем true.

Добавить осмысленные конструкторы (в том числе, будет удобно иметь конструктор из контейнера/массива, который использует std::begin и std::end из <iterator> для инициализации current и end.

Не забудьте обновить свою ветку по main.

**Comment by kuvshinovdr** [comment]
Выполнено. Файл source/stl_iterator.hpp добавлен в main.

**Comment by ChernyshevMikhail** [comment]
Задача принята?

**Comment by kuvshinovdr** [comment]
Да, раз написано "выполнено".
