### ISSUE TITLE
Dense_bit_iterator

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#5]
Создать файл source/dense_bit_iterator.cpp (в заголовке ошибся: сначала dense, потом bit).
В нём разместить класс ogxx::Dense_bit_iterator: public ogxx::Basic_iterator&lt;bool&gt;.
Данный итератор должен перечислять биты последовательности бит, заданной массивом значений unsigned.
Позиция бита задаётся unsigned const* word и int bit, т.е. указателем на "слово" и номером бита в "слове".
Всего хранится две позиции бит: текущая и конечная.

Реализовать метод next.

Перед началом работы не забудьте обновить свою ветку по ветке main.

**Comment by kuvshinovdr** [comment]
Класс Dense_bit_iterator требуется для реализации других задач, желательно поскорее его получить.

**Comment by kuvshinovdr** [comment]
Добавить поле stride (шаг между битами). По умолчанию 1. Это позволит ходить по столбцам и диагоналям бит-матрицы.

**Comment by tsay-a-vensky** [comment]
Загрузил файл, это то, что я был должен сделать или нужно что-то добавить?

**Comment by kuvshinovdr** [comment]
1. Файл переименовать dense_bit_iterator.cpp, commit & push.
2. Заменить
```cpp
#include "matrix.hpp"
```
на
```cpp
#include <ogxx/iterator.hpp>
```
3. Все int заменить на size_t.
4. currentbit должен увеличиваться на stride, а не на 1.
5. Метод next должен соответствовать интерфейсу:
```cpp
bool next(bool & value) override
```
Возвращать истину, если итератор ещё не дошёл до конца, ложь -- если дошёл.
Если не дошёл до конца -- извлекать бит и записывать его значение в value.

**Comment by tsay-a-vensky** [comment]
Правильно ли я обращаюсь ко  значению value? вроде раз word = массив, то по позиции currentbit я же получаю значение бита?

**Comment by kuvshinovdr** [comment]
Нет.
```cpp
word[currentbit]
```
обращается к значению типа unsigned в массиве, на который указывает word.
Нам же нужно извлечь один бит.
Если unsigned имеет ширину word_bits (обычно это 32), то извлечь бит можно так:
```cpp
(word[currentbit / word_bits] >> (currentbit % word_bits)) & 1
```
Определить константу word_bits можно так:
```cpp
constexpr unsigned word_bits = sizeof(unsigned) * CHAR_BIT;
```

**Comment by kuvshinovdr** [comment]
Изначально было правильно: \>\>. На паре я поменял на неправильный вариант!

**Comment by kuvshinovdr** [comment]
Задание выполнено, код добавлен в main.
