### ISSUE TITLE
Symmetric_dense_bit_matrix

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#6]
Создать файл source/symmetric_dense_bit_matrix.cpp.
В нём разместить класс ogxx::Symmetric_dense_bit_matrix : public ogxx::Bit_matrix.
В качестве хранилища бит использовать vector&lt;unsigned&gt;.
Не vector&lt;bool&gt; потому, что vector&lt;bool&gt; не позволяет эффективно работать с диапазонами бит.

Матрица квадратная и симметрическая, поэтому храним только половину. Вопрос -- что делать, если будет вызов reshape с не квадратным размером? В принципе, можно бросить исключение.

Реализовать методы:
* shape()
* reshape(Matrix_shape) (о содержимом можно не заботиться, т.е. можно использовать vector::resize)
* get(Matrix_index position)
* set(Matrix_index position, bool value)
* flip(Matrix_index position)
* fill(bool value)

Перед началом работы не забудьте обновить свою ветку по main (через rebase).

Можно скооперироваться с Романом Тимашевым: у него прямоугольная бит-матрица.

**Comment by kuvshinovdr** [comment]
Интерфейс Bit_matrix несколько расширен, но методы, возвращающие итераторы пока делать не надо.

**Comment by Gilos03** [comment]
Сделал реализацию, вопрос только в том, Bit_matrix абстрактный класс, нужно ли делать переопределение всех методов в моей реализации?

**Comment by kuvshinovdr** [comment]
Да, всех, которые сможете. Если не сможете -- надо определить заглушку, бросающую исключение вида:
```cpp
throw std::logical_error("My_class::my_method: not implemented.");
```

Там можно проще set/get написать (обменять местами индексы row и col, если они относятся к "симметричной части", потом тот же код), но пока я не понял, храните ли вы лишь половину матрицы или всю, потому что bit_contain.resize выделяет место под матрицу целиком, а не под половину.

**Comment by Gilos03** [comment]
Хорошо постараюсь сегодня - завтра переделать!

**Comment by Gilos03** [comment]
В new version, теперь храним только нижнюю часть матрицы, переделал методы set, get и fill теперь в них производится замена индексов row и col, реализовал метод copy остальные методы реализованы заглушками.

**Comment by kuvshinovdr** [comment]
1. Для случая row < col (в этом случае хранится верхний треугольник без главной диагонали) можно вычислить номер бита по формуле:
```cpp
((row * ((n << 1) - (row + 3))) >> 1) + (col - 1)
```
где n -- размер матрицы (== rows == cols).
2. Нужно проверять, является ли shape квадратным.

**Comment by Gilos03** [comment]
Добавил вычисление бита по формуле, не совсем понятно, что вы подразумеваете под проверкой является ли shape квадратной, вроде эта проверка есть:
` if (!shape.is_valid() || shape.rows != shape.cols) {
                throw std::invalid_argument("Symmetric_dense_bit_matrix::reshape: shape is invalid or not square")
            }`

**Comment by kuvshinovdr** [comment]
Хорошо.
```cpp
                auto const index = (row < col) ?
                        (((row * ((n << 1) - (row + 3))) >> 1) + (col - 1)) :
                        (col * n + row);
```
-- разумно обменять row и col, если col < row а затем посчитать index по формуле.

**Comment by Gilos03** [comment]
В UPD 3 учел замечание, переделал.

**Comment by kuvshinovdr** [comment]
Код принят в main.
