### ISSUE TITLE
Adjacency_list_hashtable

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#67]
Создать в source файл adjacency_list_hashtable.cpp. В нём создать класс Adjacency_list_hashtable, реализующий Adjacency_list на основе std::unordered_map\<Scalar_index, std::unique_ptr\<Adjacency\>\>. В качестве примера можно использовать заготовку adjacency_list_vector.cpp, выложенную в source.

**Comment by KonstantinPM201** [comment]
Здравствуйте. Вроде как дописал класс `Adjacency_list_hashtable`. Можете проверить.

**Comment by kuvshinovdr** [comment]
Проверил. Код добавлен в main. Почему-то Github Desktop у меня не хочет открывать вашу ветку из-за какой-то ошибки с Doxygen Awesome. Загадочно.

**Comment by KonstantinPM201** [comment]
А что за ошибка?
