### ISSUE TITLE
Dense_st_matrix

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#7]
Создать файл source/dense_st_matrix.cpp.
В нём разместить класс ogxx::Dense_st_matrix&lt;ST&gt; : public ogxx::St_matrix&lt;ST&gt;.
В качестве хранилища элементов матрицы использовать vector&lt;ST&gt; (упакованный двумерный массив).

Реализовать методы:
* shape()
* reshape(Matrix_shape) (о содержимом можно не заботиться, т.е. можно использовать vector::resize)
* get(Matrix_index position)
* set(Matrix_index position, ST value)
* fill(ST value)

Перед началом работы не забудьте обновить свою ветку по main (через rebase).

**Comment by kuvshinovdr** [comment]
Класс Dense_st_matrix требуется для реализации другой задачи, желательно поскорее его получить.

**Comment by kuvshinovdr** [comment]
Интерфейс St_matrix обновился, но из добавленных методов сейчас можно сделать только copy. Остальные реализовать заглушками.

**Comment by EgorLubnin** [comment]
Добрый вечер!
Сделал и доработал свою задачу.

**Comment by EgorLubnin** [comment]
Добрый вечер!
Доработал метод copy для dense_st_matrix.

**Comment by EgorLubnin** [comment]
Здравствуйте, Дмитрий Рустамович!
Написал test_dense_st_matrix.cpp

**Comment by EgorLubnin** [comment]
Добрый день, Дмитрий Рустамович!
1) Исправил файл test_dense_st_matrix, переделав аргументы, которые принимают get and set.
2) Добавил имя автора в файле dense_st_matrix.

**Comment by kuvshinovdr** [comment]
Задание принято, код добавлен в main.
