### ISSUE TITLE
Random_choice_bag

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#73]
Для задачи #71. Создать класс Random_choice_bag\<T\>, реализующий интерфейс Bag\<T\> и позволяющий извлекать элементы в случайном порядке. Его представляется разумным реализовать поверх std::vector\<T\>. Элементы добавлять всегда в конец, а извлекать из случайно выбранной позиции. Для этого можно вычислить псевдослучайный индекс, обменять элемент с вычисленным индексом с последним элементом вектора и удалить его (уже с конца), что позволит эффективно (за амортизированное постоянное время) добавлять и удалять элементы. Использовать std::default_random_engine и std::[uniform_int_distribution](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution) из \<[random](https://en.cppreference.com/w/cpp/numeric/random)\>.

**Comment by Alexanders2007** [comment]
Добавлены реализации методов is_emtpy, size и iterate

**Comment by kuvshinovdr** [comment]
Внесены некоторые правки и файл переименован (в вашей ветке). Код добавлен к main. Задание принято.
