### ISSUE TITLE
floyd_warshall

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#76]
Создать файлы include/ogxx/floyd_warshall.hpp и source/floyd_warshall.cpp.
Объявить в первом из них и определить во втором из них функции

```cpp
auto floyd_warshall_only_matrix(Int_matrix const& distances) -> Int_matrix_uptr;

auto floyd_warshall_only_matrix(Float_matrix const& distances) -> Float_matrix_uptr;
```

Данные функции должны считать матрицы расстояний между вершинами по матрицам длин рёбер, используя [алгоритм Флойда-Уоршелла](https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%A4%D0%BB%D0%BE%D0%B9%D0%B4%D0%B0_%E2%80%94_%D0%A3%D0%BE%D1%80%D1%88%D0%B5%D0%BB%D0%BB%D0%B0) без предшественников (упрощённый вариант -- только матрицы расстояний, напоминает умножение матриц).

**Comment by RomanTimashev** [comment]
а какое отличие есть в работе с Float matrix и Int matrix

**Comment by kuvshinovdr** [comment]
Никакого, только тип. Там в cpp-файле можно написать функцию-шаблон, которая решает задачу для St_matrix<T> и вызывать её из этих функций.

**Comment by RomanTimashev** [comment]
а предполагается ли то что матрица квадратная на входе?

**Comment by kuvshinovdr** [comment]
Да.

**Comment by RomanTimashev** [comment]
что то есть на коленках написал

**Comment by RomanTimashev** [comment]
все поправил 20.12.23

**Comment by kuvshinovdr** [comment]
1. Давайте будем бросать исключение, если матрица не квадратная.
2. Тип индекса в циклах должен быть Scalar_index, а не int.
3. Устанавливать значение элемента через get(i, j) = ... не получится, надо писать set(i, j, ...).
4. Переменная result имеет тип указателя, поэтому обращаться к ней надо через стрелку -\>.
5. Надо реализовать функции, указанные в задании (не шаблонные), которые будут вызывать шаблонную функцию.

**Comment by RomanTimashev** [comment]
поправил все что указано, но не понимаю почему редактор пишет что параметризовать не получается

**Comment by kuvshinovdr** [comment]
А зачем автором ставите меня?
Надо убрать функцию-шаблон из hpp-файла. Убрать второй параметр (он не нужен).

Итак,
```cpp
   auto floyd_warshall_only_matrix_ST( const ogxx::St_matrix<ST>& distances, ST)
```
->
```cpp
   auto floyd_warshall_only_matrix_ST( const ogxx::St_matrix<ST>& distances) -> St_matrix_uptr<ST>
```

Проверять размер надо через shape:
```cpp
if(!distances.is_square()) 
```
->
```cpp
if(!distances.shape().is_square()) 
```

Опечатка:
```cpp
auto result = distance.copy();
```
->
```cpp
auto result = distances.copy();
```

и
```cpp
for (Scalar_index j = 0; j < n.cols ++j)
```
->
```cpp
for (Scalar_index j = 0; j < n.cols; ++j)
```

Надо помочь компилятору (то ли MSVC тупит/глючит, то ли стандарт так велит), добавив явно типы результата:
```cpp
auto floyd_warshall_only_matrix(Int_matrix const& distances) {
```
->
```cpp
auto floyd_warshall_only_matrix(Int_matrix const& distances) -> Int_matrix_uptr {
```
и аналогично вторую функцию.

Наконец, обнаружилось, что я забыл указать const у метода St_matrix::copy. Так что придётся обновить ветку по main (внесены значимые поправки).

**Comment by RomanTimashev** [comment]
поправил

**Comment by RomanTimashev** [comment]
еще хотел спросить сколько примерно баллов вы мне поставите чтоб хоть чуть чуть представлять будет автомат или нет

**Comment by kuvshinovdr** [comment]
100, уже поставил в таблицу.

**Comment by kuvshinovdr** [comment]
Код добавлен в main.
