### ISSUE TITLE
Symmetric_dense_st_matrix

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#8]
Создать файл source/symmetric_dense_st_matrix.cpp.
В нём разместить класс ogxx::Symmetric_dense_st_matrix&lt;ST&gt; : public ogxx::St_matrix&lt;ST&gt;.
В качестве хранилища использовать vector&lt;ST&gt;.

Матрица квадратная и симметрическая, поэтому храним только половину. В случае вызова reshape с не квадратным размером  можно бросить исключение.

Реализовать методы:
* shape()
* reshape(Matrix_shape) (о содержимом можно не заботиться, т.е. можно использовать vector::resize)
* get(Matrix_index position)
* set(Matrix_index position, bool value)
* flip(Matrix_index position)
* fill(bool value)

Перед началом работы не забудьте обновить свою ветку по main (через rebase).

**Comment by KonstantinPM201** [comment]
Делать Rebase было страшно.
Кажется, что получилось.

**Comment by kuvshinovdr** [comment]
Если делаете с помощью github desktop, то там можно вместо rebase выбрать update. 
Если делаете из консоли, то можно merge:

git checkout pm2-martianov-k-s
git merge main

**Comment by kuvshinovdr** [comment]
Интерфейс St_matrix обновился, но из добавленных методов сейчас можно сделать только copy. Остальные реализовать заглушками.

**Comment by KonstantinPM201** [comment]
Некоторые методы были удалены?
Их надо удалить?

**Comment by kuvshinovdr** [comment]
Нет.

**Comment by KonstantinPM201** [comment]
Я написал оператор copy. Поправил формулу в get.

**Comment by KonstantinPM201** [comment]
1. Исправил.
2. Добавил
3. Надо подумать.

Правильно я понимаю, что надо создавать не
`auto copied_matrix = std::make_unique<Symmetric_dense_st_matrix<ST>>(window.shape.rows);`
А надо делать с St_matrix. И если так, то у St_matrix есть конструктор для создания матрицы определенного размера?

**Comment by kuvshinovdr** [comment]
Да, надо St_matrix. Конструктора пока нет. St_matrix -- абстрактный класс, нужны фабричные методы, чтобы создавать конкретные объекты того или иного типа. Пока Dense_st_matrix не готов полностью (хотя почти готов).

**Comment by kuvshinovdr** [comment]
Задание выполнено, код добавлен в main.
